[package]
name = "fixer-sdk"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
fixer-core = { path = "../fixer-core" }
fixer-http = { path = "../fixer-http" }
futures-util.workspace = true
reflink-copy.workspace = true
thiserror.workspace = true
tokio.workspace = true

[dev-dependencies]
fixer-provider-anilist = { path = "../fixer-provider-anilist" }
fixer-provider-bangumi = { path = "../fixer-provider-bangumi" }
fixer-provider-local = { path = "../fixer-provider-local" }
fixer-provider-musicbrainz = { path = "../fixer-provider-musicbrainz" }
fixer-provider-tmdb = { path = "../fixer-provider-tmdb" }
fixer-writer-local = { path = "../fixer-writer-local" }
wiremock.workspace = true
trybuild.workspace = true
serde_json.workspace = true
tempfile.workspace = true

[[example]]
name = "sdk_movie"
path = "../../examples/sdk_movie.rs"
