[package]
name = "fixer-sdk"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
fixer-core = { path = "../fixer-core" }
fixer-http = { path = "../fixer-http" }
futures-util.workspace = true
reflink-copy.workspace = true
thiserror.workspace = true
tokio.workspace = true

[dev-dependencies]
fixer-provider-local = { path = "../fixer-provider-local" }
trybuild.workspace = true
serde_json.workspace = true
tempfile.workspace = true
