[package]
name = "fixer-provider-anilist"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
description.workspace = true
repository.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true

[lints]
workspace = true

[dependencies]
fixer-core = { path = "../fixer-core" }
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
url.workspace = true

[dev-dependencies]
fixer-http = { path = "../fixer-http" }
tokio.workspace = true
wiremock.workspace = true
