/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as ProvidersRouteImport } from './routes/providers'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as JobsIndexRouteImport } from './routes/jobs/index'
import { Route as JobsJobIdIndexRouteImport } from './routes/jobs/$jobId/index'
import { Route as JobsJobIdPlanRouteImport } from './routes/jobs/$jobId/plan'
import { Route as JobsJobIdReviewRouteImport } from './routes/jobs/$jobId/review'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvidersRoute = ProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsIndexRoute = JobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsJobIdIndexRoute = JobsJobIdIndexRouteImport.update({
  id: '/jobs/$jobId/',
  path: '/jobs/$jobId/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsJobIdPlanRoute = JobsJobIdPlanRouteImport.update({
  id: '/jobs/$jobId/plan',
  path: '/jobs/$jobId/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsJobIdReviewRoute = JobsJobIdReviewRouteImport.update({
  id: '/jobs/$jobId/review',
  path: '/jobs/$jobId/review',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/library': typeof LibraryRoute
  '/providers': typeof ProvidersRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/templates': typeof TemplatesRoute
  '/jobs/': typeof JobsIndexRoute
  '/jobs/$jobId/plan': typeof JobsJobIdPlanRoute
  '/jobs/$jobId/review': typeof JobsJobIdReviewRoute
  '/jobs/$jobId/': typeof JobsJobIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/library': typeof LibraryRoute
  '/providers': typeof ProvidersRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/templates': typeof TemplatesRoute
  '/jobs': typeof JobsIndexRoute
  '/jobs/$jobId/plan': typeof JobsJobIdPlanRoute
  '/jobs/$jobId/review': typeof JobsJobIdReviewRoute
  '/jobs/$jobId': typeof JobsJobIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/library': typeof LibraryRoute
  '/providers': typeof ProvidersRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/templates': typeof TemplatesRoute
  '/jobs/': typeof JobsIndexRoute
  '/jobs/$jobId/plan': typeof JobsJobIdPlanRoute
  '/jobs/$jobId/review': typeof JobsJobIdReviewRoute
  '/jobs/$jobId/': typeof JobsJobIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/library'
    | '/providers'
    | '/search'
    | '/settings'
    | '/templates'
    | '/jobs/'
    | '/jobs/$jobId/plan'
    | '/jobs/$jobId/review'
    | '/jobs/$jobId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/library'
    | '/providers'
    | '/search'
    | '/settings'
    | '/templates'
    | '/jobs'
    | '/jobs/$jobId/plan'
    | '/jobs/$jobId/review'
    | '/jobs/$jobId'
  id:
    | '__root__'
    | '/'
    | '/library'
    | '/providers'
    | '/search'
    | '/settings'
    | '/templates'
    | '/jobs/'
    | '/jobs/$jobId/plan'
    | '/jobs/$jobId/review'
    | '/jobs/$jobId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LibraryRoute: typeof LibraryRoute
  ProvidersRoute: typeof ProvidersRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  TemplatesRoute: typeof TemplatesRoute
  JobsIndexRoute: typeof JobsIndexRoute
  JobsJobIdPlanRoute: typeof JobsJobIdPlanRoute
  JobsJobIdReviewRoute: typeof JobsJobIdReviewRoute
  JobsJobIdIndexRoute: typeof JobsJobIdIndexRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/providers': {
      id: '/providers'
      path: '/providers'
      fullPath: '/providers'
      preLoaderRoute: typeof ProvidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/': {
      id: '/jobs/'
      path: '/jobs'
      fullPath: '/jobs/'
      preLoaderRoute: typeof JobsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$jobId/': {
      id: '/jobs/$jobId/'
      path: '/jobs/$jobId'
      fullPath: '/jobs/$jobId/'
      preLoaderRoute: typeof JobsJobIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$jobId/plan': {
      id: '/jobs/$jobId/plan'
      path: '/jobs/$jobId/plan'
      fullPath: '/jobs/$jobId/plan'
      preLoaderRoute: typeof JobsJobIdPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$jobId/review': {
      id: '/jobs/$jobId/review'
      path: '/jobs/$jobId/review'
      fullPath: '/jobs/$jobId/review'
      preLoaderRoute: typeof JobsJobIdReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LibraryRoute: LibraryRoute,
  ProvidersRoute: ProvidersRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  TemplatesRoute: TemplatesRoute,
  JobsIndexRoute: JobsIndexRoute,
  JobsJobIdPlanRoute: JobsJobIdPlanRoute,
  JobsJobIdReviewRoute: JobsJobIdReviewRoute,
  JobsJobIdIndexRoute: JobsJobIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
